name = "commonground-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"
account_id = "6d42189fc4724a2d0ad8650b53814692"

[[d1_databases]]
binding = "DB"
database_name = "commonground"
database_id = "dfcabaeb-af61-48fa-817f-ea345b8f27b6"

[vars]
ENVIRONMENT = "production"
PLATFORM_NAME = "CommonGround"
